#!/bin/bash

# Stop sbideo server
stop sbideo-server

# Stop sbideo transcoding
stop sbideo-transcode

# Remove sbideo startup configuration files
rm /etc/init/sbideo-server.conf /etc/init/sbideo-transcode.conf
