#!/bin/bash

# Stop sbideo server
systemctl stop sbideo-server.service 

# Stop sbideo transcoding
systemctl stop sbideo-transcode.service

# Disable start on bootup for sbideo server
systemctl disable sbideo-server.service 

# Remove sbideo startup configuration files
rm /etc/systemd/system/sbideo-server.service /etc/systemd/system/sbideo-transcode.service
